# Generated by Django 3.2.3 on 2021-05-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationId', models.IntegerField()),
                ('thread_author', models.CharField(max_length=150)),
                ('thread_author_pp', models.ImageField(upload_to='img/pp')),
                ('thread_tweets', models.CharField(max_length=2000)),
                ('thread_time', models.DateTimeField()),
            ],
        ),
    ]
